### ISSUE TITLE
Change to CC0

### ISSUE THREAD

**Issue by kemitchell** [sindresorhus/spdx-license-list#11]
@danielhusar, @sschuberth, are you willing to apply Creative Commons CC0 to your contributions to this package, as well? See https://github.com/sindresorhus/spdx-license-list/commit/16d0a9fbbdfd6370b412c16392dbd35c26a689b0

I see that you've each made only one or two commits here, but they look significant! I'm not sure what, if any, of the current code derives from yours. But it would be nice to be clear about the terms change.

**Comment by sschuberth** [comment]
I'm fine with re-licensing my contributions under CC0.

**Comment by jhabdas** [comment]
Better yet WTFPL and fuggetaboutit

By the way https://github.com/spdx/license-list-data/blob/master/json/licenses.json
