### ISSUE TITLE
Thoughts on license-generator (string variable interpolation)?

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/spdx-license-list#12]
Currently there exists a package <https://github.com/arshad/license-generator> which is outdated/does not have all the licenses available I believe.

@sindresorhus I was curious if you experimented at all with interpolation of variable names `<name>`, `<year>`, etc.  It'd be very convenient for generating packages

I do understand though that NPM, GitHub, and Choose a License/Shields.io look at `package.json` for license prop - though I think it seems a standard to also include a LICENSE file?

**Comment by sindresorhus** [comment]
No opinion. I personally use MIT License for everything so a license generator wouldn't be useful for me.

**Comment by JacobDB** [comment]
I'd be interested in this as well.

**Comment by kemitchell** [comment]
[`licensor`](https://www.npmjs.com/package/licensor) generates and fills out `LICENSE` templates and header comments for the most popular license choices.
