### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by ddgenome** [sindresorhus/spdx-license-list#19]
I have created TypeScript typings for this package. Would you prefer I create a PR to add them here or add them to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by sindresorhus** [comment]
I'm happy to host them here if you're willing to follow [this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide).

Some examples:
- https://github.com/sindresorhus/semver-regex/commit/039944bb5b3876913171b895488874b5c200e458
- https://github.com/sindresorhus/global-dirs/commit/0aae4d64887f77af94c4fb7ca12aa9f93c0a8291
- https://github.com/sindresorhus/md5-hex/commit/bbbfeff840f26973fbffc16d4863ae6d120079f3

**Comment by ddgenome** [comment]
Crikey! I'll see if I can create something that measures up.
