### ISSUE TITLE
Generate licenses?

### ISSUE THREAD

**Issue by pluma** [sindresorhus/spdx-license-list#9]
Can the license text be used to generate licenses? It seems that the text actually contains not just the full license text but SPDX markup for matching purposes. Is there a parser for this markup that could be fed with user-provided settings?

**Comment by sindresorhus** [comment]
Yes, but no idea how. This is just a module for getting the license text. I'm not involved with SPDX.

Maybe @kemitchell knows.

**Comment by kemitchell** [comment]
SPDX is working on more systematically formatted templates. I think they're pretty far  along, and that they're using an XML schema. It may be on GitHub now; you could check the mailing list archive for the latest.

If you need something lighter weight but less complete, you can have a look at what I've done with the licensor package and the jslicense org on GitHub.

**Comment by pluma** [comment]
Thanks for the swift response!

Actually this discussion helps me a fair bit I think: https://github.com/sindresorhus/spdx-license-list/issues/6#issuecomment-150606727

The only problem seems to be that some licenses aren't in template form (yet?), especially the more obscure licenses and variants.
